CREATE TABLE public.employees (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  trade TEXT NOT NULL DEFAULT 'HELPER',
  id_number TEXT NOT NULL DEFAULT '',
  hourly_rate NUMERIC NOT NULL DEFAULT 0,
  status TEXT NOT NULL DEFAULT 'Active' CHECK (status IN ('Active','Holiday','Cancelled')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.employees TO anon, authenticated;
GRANT ALL ON public.employees TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.employees_id_seq TO anon, authenticated, service_role;
ALTER TABLE public.employees ENABLE ROW LEVEL SECURITY;
CREATE POLICY "employees_public_all" ON public.employees FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

CREATE TABLE public.payroll_batches (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  month TEXT NOT NULL,
  site TEXT NOT NULL DEFAULT '',
  foreman TEXT NOT NULL DEFAULT '',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.payroll_batches TO anon, authenticated;
GRANT ALL ON public.payroll_batches TO service_role;
ALTER TABLE public.payroll_batches ENABLE ROW LEVEL SECURITY;
CREATE POLICY "payroll_batches_public_all" ON public.payroll_batches FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

CREATE TABLE public.payroll_lines (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  batch_id UUID NOT NULL REFERENCES public.payroll_batches(id) ON DELETE CASCADE,
  employee_id BIGINT NOT NULL REFERENCES public.employees(id) ON DELETE CASCADE,
  month TEXT NOT NULL,
  foreman TEXT NOT NULL DEFAULT '',
  hours NUMERIC NOT NULL DEFAULT 0,
  rate NUMERIC NOT NULL DEFAULT 0,
  food_deduction NUMERIC NOT NULL DEFAULT 0,
  prev_advance NUMERIC NOT NULL DEFAULT 0,
  new_advance NUMERIC NOT NULL DEFAULT 0,
  other_deduction NUMERIC NOT NULL DEFAULT 0,
  net_salary NUMERIC NOT NULL DEFAULT 0,
  paid NUMERIC NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT payroll_lines_unique_emp_month UNIQUE (employee_id, month)
);
CREATE INDEX payroll_lines_batch_idx ON public.payroll_lines(batch_id);
CREATE INDEX payroll_lines_emp_month_idx ON public.payroll_lines(employee_id, month);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.payroll_lines TO anon, authenticated;
GRANT ALL ON public.payroll_lines TO service_role;
ALTER TABLE public.payroll_lines ENABLE ROW LEVEL SECURITY;
CREATE POLICY "payroll_lines_public_all" ON public.payroll_lines FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

CREATE OR REPLACE FUNCTION public.payroll_lines_sync_month()
RETURNS TRIGGER
LANGUAGE plpgsql
SET search_path = public
AS $$
BEGIN
  SELECT b.month INTO NEW.month FROM public.payroll_batches b WHERE b.id = NEW.batch_id;
  RETURN NEW;
END;
$$;
CREATE TRIGGER payroll_lines_sync_month_trg
BEFORE INSERT OR UPDATE OF batch_id ON public.payroll_lines
FOR EACH ROW EXECUTE FUNCTION public.payroll_lines_sync_month();